Testing the redirect

diff --git a/.github/workflows/tc_blink_diff_compare.yml b/.github/workflows/tc_blink_diff_compare.yml
--- a/.github/workflows/tc_blink_diff_compare.yml
+++ b/.github/workflows/tc_blink_diff_compare.yml
@@ -151,11 +151,11 @@ jobs:
       - name: Get id of a workflow with screenshot artifacts
         id: get-run-id
         run: |
-          curl -L \
+          echo 'ARTIFACT_SOURCE_RUN_ID=curl -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ github.token }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          "https://api.github.com/repos/${{ github.respository }}/environments/artifacts/variables/ARTIFACT_SOURCE_RUN_ID" >> $GITHUB_OUTPUT
+          "https://api.github.com/repos/${{ inputs.respository }}/environments/artifacts/variables/ARTIFACT_SOURCE_RUN_ID"' >> $GITHUB_OUTPUT
 
       - uses: actions/download-artifact@v4
         if: success()
@@ -164,7 +164,7 @@ jobs:
           pattern: ${{ matrix.resolution }}
           github-token: ${{ github.token }}
           repository: ${{ inputs.repository }}
-          run-id: ${{ steps.get-run-id.outputs.id }}
+          run-id: ${{ steps.get-run-id.outputs.ARTIFACT_SOURCE_RUN_ID }}
 
       - uses: Platform-OS/gh-action-run-tc-blink-diff@gh-artifacts
         name: Compare screenshots for ${{ matrix.resolution }} resolution
@@ -176,86 +176,87 @@ jobs:
           resolution: ${{ matrix.resolution }}
           test-name: tc-${{ matrix.resolution }}-snapshots-diff
 
-  notify:
-    needs: ["reserve-ci-instance", "deploy", "compare"]
-    if: ${{ success() || failure() }}
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
-    env:
-      CI: true
-      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
-      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
-      MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}
-      UPLOAD_HOST: https://tests.qa0.oregon.platformos.com
-    steps:
+  #notify:
+  #  needs: ["reserve-ci-instance", "deploy", "compare"]
+  #  if: ${{ success() || failure() }}
+  #  runs-on: ubuntu-latest
+  #  timeout-minutes: 5
+  #  env:
+  #    CI: true
+  #    MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
+  #    MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
+  #    MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}
+  #    UPLOAD_HOST: https://tests.qa0.oregon.platformos.com
+  #  steps:
 
-      - name: Send notification to Slack
-        id: notify-slack
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          payload: |
-            {
-              "channel": "test-reports",
-              "text": "Visual regression tests",
-              "blocks": [
-                {
-                  "type": "header",
-                  "text": {
-                    "type": "plain_text",
-                    "text": "testcafe blink diff visual regression tests"
-                  }
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Repository:*\n${{ github.repository }}"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Branch:*\n${{ github.ref_name }}"
-                    }
-                  ]
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Commit:*\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Actor:*\n${{ github.actor }}\n"
-                    }
-                  ]
-                },
-                {
-                  "type": "section",
-                  "text": {
-                    "type": "mrkdwn",
-                    "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View action run>"
-                  }
-                },
-                {
-                  "type": "section",
-                  "text": {
-                    "type": "mrkdwn",
-                      "text": "${{ env.desktop-result-icon }} <${{ needs.compare.outputs.desktop-diff-report-url }}|View test report for desktop resolution>\n${{ env.mobile-result-icon }} <${{ needs.compare.outputs.mobile-diff-report-url }}|View test report for mobile resolution>\n"
-                  }
-                }
-              ]
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
-          desktop-result-icon: ${{ needs.compare.outputs.desktop-diff-conclusion == 'success' && ':white_check_mark:' || ':x:' }}
-          mobile-result-icon: ${{ needs.compare.outputs.mobile-diff-conclusion == 'success' && ':white_check_mark:' || ':x:' }}
+  #    - name: Send notification to Slack
+  #      id: notify-slack
+  #      uses: slackapi/slack-github-action@v1.24.0
+  #      with:
+  #        payload: |
+  #          {
+  #            "channel": "test-reports",
+  #            "text": "Visual regression tests",
+  #            "blocks": [
+  #              {
+  #                "type": "header",
+  #                "text": {
+  #                  "type": "plain_text",
+  #                  "text": "testcafe blink diff visual regression tests"
+  #                }
+  #              },
+  #              {
+  #                "type": "section",
+  #                "fields": [
+  #                  {
+  #                    "type": "mrkdwn",
+  #                    "text": "*Repository:*\n${{ github.repository }}"
+  #                  },
+  #                  {
+  #                    "type": "mrkdwn",
+  #                    "text": "*Branch:*\n${{ github.ref_name }}"
+  #                  }
+  #                ]
+  #              },
+  #              {
+  #                "type": "section",
+  #                "fields": [
+  #                  {
+  #                    "type": "mrkdwn",
+  #                    "text": "*Commit:*\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
+  #                  },
+  #                  {
+  #                    "type": "mrkdwn",
+  #                    "text": "*Actor:*\n${{ github.actor }}\n"
+  #                  }
+  #                ]
+  #              },
+  #              {
+  #                "type": "section",
+  #                "text": {
+  #                  "type": "mrkdwn",
+  #                  "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View action run>"
+  #                }
+  #              },
+  #              {
+  #                "type": "section",
+  #                "text": {
+  #                  "type": "mrkdwn",
+  #                    "text": "${{ env.desktop-result-icon }} <${{ needs.compare.outputs.desktop-diff-report-url }}|View test report for desktop resolution>\n${{ env.mobile-result-icon }} <${{ needs.compare.outputs.mobile-diff-report-url }}|View test report for mobile resolution>\n"
+  #                }
+  #              }
+  #            ]
+  #          }
+  #      env:
+  #        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+  #        desktop-result-icon: ${{ needs.compare.outputs.desktop-diff-conclusion == 'success' && ':white_check_mark:' || ':x:' }}
+  #        mobile-result-icon: ${{ needs.compare.outputs.mobile-diff-conclusion == 'success' && ':white_check_mark:' || ':x:' }}
 
   cleanup:
     if: ${{ always() }}
-    needs: ["reserve-ci-instance", "deploy", "compare", "notify"]
+    #needs: ["reserve-ci-instance", "deploy", "compare", "notify"]
+    needs: ["reserve-ci-instance", "deploy", "compare"]
     runs-on: ubuntu-latest
     container: alpine:3.15
     steps:
